### PR TITLE
fix(_controller.spec.js): add ui-router dependency - patch

### LINKED ISSUE #1: Breaks unit tests
Running the generator causes the unit tests to fail. It appears that adding `ui.router` as a dependency to the angular module in the generated route resolves the issue.

### PR DESCRIPTION
**Pull request by Acefox17**
Fixes #1

### CODE REVIEW

**Comment by lowe0292** [comment]
@Acefox17 Something's causing the unit tests to fail. Any idea what it is?

**Comment by Acefox17** [comment]
@lowe0292  In the logs I keep getting the errors that it's can't find a bunch of modules, adding them to dev dependencies is fixing each individual one, but I think they should be included recursively. I noticed a warning while the job was running that the node and nmp versions were older than recommended (0.10.X and 1.X respectively). Maybe upgrading those would do the trick. I'm just adding them individually till then.

**Comment by Acefox17** [comment]
@lowe0292 now I'm getting this error

The command "git push origin gh-pages -fq > /dev/null" exited with 128.

**Comment by lowe0292** [comment]
@Acefox17 here's what I see in the logs:

```
git push origin gh-pages -fq > /dev/null
remote: Permission to castle-dev/generator-le-page.git denied to 495d02d1d67ba32ecd9d53a836239c7bbb13f066.
fatal: unable to access 'https://495d02d1d67ba32ecd9d53a836239c7bbb13f066@github.com/castle-dev/generator-le-page.git/': The requested URL returned error: 403
```

It's trying to push the auto-generated docs to the `gh-pages` branch and can't. Maybe Travis doesn't have write access on the repo?

**Comment by Acefox17** [comment]
@lowe0292 I looked at the castle-travis GitHub account. It seems to have read access only for all the repos, so I didn't want to change it. I'll ask you about it tomorrow.

**Comment by Acefox17** [comment]
@lowe0292, This isn't a high priority, but if you could help figure out how to get travis to write to gh-pages that would be a relief, le-data-service is having the same travis issue.

**Comment by Acefox17** [comment]
@lowe0292 You can pull this now! :tada:

**Pull request merged**
